spring: 
  rabbitmq: 
    host: localhost
    port: 5672
    username: guest
    password: guest
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    driverClassName: org.h2.Driver
    username: sa
    password: 
      
  zipkin:
    enabled: true
    base-url: http://localhost:9411/
    
server: 
  port: 8000
  
welcome:
  message:
    WF: Welcome to Wells Fargo
    BOA: Welcome to Bank Of America
  
 

eureka: 
  client: 
    fetch-registry: true
    register-with-eureka: true
    service-url: 
      defaultZone: http://localhost:8761/eureka  



management: 
  endpoints:
    web:
      exposure:
        include: '*'