practice:
   customer:
      greeting_message: Welcome Buddy DEV
      
management:
   endpoints:
      web:
         exposure:
            include: "*"

eureka:
   client:
      register-with-eureka: false
      fetch-registry: false
      service-url:
         defaultZone: http://localhost:8761/eureka
      
spring:
  rabbitmq:
    host: myrabbit
    port: 5672
    username: guest
    password: guest

