spring: 
  rabbitmq: 
    host: localhost
    port: 5672
    username: guest
    password: guest
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
  datasource:
    username: sa
    password: 
    
server: 
  port: 8000
  
welcome:
  message:
    WF: Welcome to Wells Fargo
    BOA: Welcome to BOA
  
 

eureka: 
  client: 
    fetch-registry: true
    register-with-eureka: true
    service-url: 
      defaultZone: http://localhost:8761/eureka  



management: 
  endpoints:
    web:
      exposure:
        include: '*'