management:
   endpoints:
      web:
         exposure:
            include: "*"

eureka:
   client:
      register-with-eureka: true
      fetch-registry: true
      service-url:
         defaultZone: http://localhost:8761/eureka
      
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

